version: "3.9"

services:
  mobile-game:
    build: .
    command: npm run start -- --tunnel --port 8081
    environment:
      EXPO_DEVTOOLS_LISTEN_ADDRESS: 0.0.0.0
      REACT_NATIVE_PACKAGER_HOSTNAME: 0.0.0.0
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "8081:8081"
    stdin_open: true
    tty: true
